manage-inc: linux
- update make/compile (fix issues visible on linux and not on darwin)
- update inc.sh (fix issues visible on linux and not on darwin)

diff --git a/make/compile b/make/compile
--- a/make/compile
+++ b/make/compile
@@ -6,19 +6,17 @@
 # 
 ###
 
-echo "--- Compiling inc.sh"
+echo "--- compiling inc.sh"
 shc -f inc.sh -o inc
-
-echo "--- Create/Update ~/bin/inc link"
-ln -sf ${PWD}/inc ~/bin/inc
-
-if [[ $(uname) == "Darwin" ]];then
-    ln -sf ${PWD}/bash_completion.d/inc /opt/homebrew/etc/bash_completion.d/
-    ln -sf ${PWD}/bash_completion.d/ops /opt/homebrew/etc/bash_completion.d/
-else
-    ln -sf ${PWD}/bash_completion.d/inc /etc/bash_completion.d/
-    ln -sf ${PWD}/bash_completion.d/ops /etc/bash_completion.d/
+if [ $? != 0 ];then
+  echo "[ERROR] compile failed"
+  exit 1
 fi
+
+echo "--- create/Update ~/bin/inc link"
+ln -sf ${PWD}/inc ~/bin/inc
+sudo ln -sf ${PWD}/bash_completion.d/inc /etc/bash_completion.d/
+sudo ln -sf ${PWD}/bash_completion.d/ops /etc/bash_completion.d/
 echo "--- compile done"
 
 #EOF
